# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: fe23dev
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: billboard-api
# "service" is the name of this project. This will also be added to your AWS resource names.
service: message-app-api

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  deploymentMethod: direct
  iam:
    role: arn:aws:iam::863518420873:role/fullaccesspeter
  httpApi:
    cors: true

functions:
  DeleteMessage:
    handler: functions/DeleteMessage/index.handler
    events:
      - httpApi:
          path: /api/message/{id}
          method: delete


  GetMessage:
    handler: functions/GetMessage/index.handler
    events:
      - httpApi:
          path: /api/message
          method: get


  PostMessage:
    handler: functions/PostMessage/index.handler
    events:
      - httpApi:
          path: /api/message
          method: post


  PutMessage:
    handler: functions/PutMessage/index.handler
    events:
      - httpApi:
          path: /api/message/{id}
          method: put

resources:
  Resources:
    DaysTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: 'message-app-db'
        AttributeDefinitions:
          - AttributeName: 'id'
            AttributeType: 'S'
        KeySchema: 
          - AttributeName: 'id'
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
